### ISSUE TITLE
Basic Example - replacing @prisma/client with cached-prisma

### ISSUE THREAD

**Issue by neil-oliver** [JoelLefkowitz/cached-prisma#2]
Hi Joel, firstly this project looks awesome and i cant believe its not something built into Prisma (although i saw one of the devs forked it).

I currently have a Vue project setup using Prisma in the middleware. [Here](https://dev.to/prisma/adding-an-api-and-database-to-your-nuxt-app-with-prisma-2nlp) is the same implementation i used, although i think the only relevant parts are that it uses Prisma client and runs the Prisma generate command. I tried to replace Prisma/client with cached-prisma however it threw errors to do with the client not being initialized yet. 

No doubt it is my fault, however i would love some more details on how to use this or a basic example. Thank you so much for your hard work on this and i really hope i can use it, it would transform my project.

**Comment by JoelLefkowitz** [comment]
Sure thing Neil, glad you like the project. I think the next step is for me to add a basic example to the readme and we'll try get your Vue project's integration up and running.

**Comment by neil-oliver** [comment]
Thanks @JoelLefkowitz. If there is anything i can do to support, i am happy to contribute. Feel free to reach out here or at neiloliverphoto@gmail.com

**Comment by JoelLefkowitz** [comment]
Sorry for delay, thanks for the offer Neil, if people open up issues with feature requests we can divide them up. I've added a minimal example section to the readme with a full set of setup instructions. If it still looks unclear please reopen this issue with suggestions.
