### ISSUE TITLE
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.

### ISSUE THREAD

**Issue by dayerelo** [JoelLefkowitz/cached-prisma#3]
# Bug Report

## Description

Hello, i am trying to make this package work in my project. I have prisma installed and doing well on its own, apart for the obvious lack of cache.
After installing the package with `npm install cached-prisma`, and replacing the client by the one put in the readme file, i get an error saying there is no prisma client generated (see below). The error comes from the node_modules folder in the cached-prisma module. It seems that on a fresh install, the prisma client used by the module is not generated. I tried running the equivalent of `npx prisma generate`, by doing `node .\node_modules\cached-prisma\node_modules\@prisma\client\scripts\postinstall.js`, to no avail.

I am still fairly new to node, so i apology if there is anything I've missed. Thanks for your help !

## Is this a regression?

I never tried this package before.

## Minimal Reproduction

db.ts, before cached-client :
```code
import * as pkg from '@prisma/client';

export const prisma = new pkg.PrismaClient();
```

db.ts, with cached-client :
```code
import { Prisma, Memcached } from 'cached-prisma';
class CustomPrisma extends Prisma {
  cacheFactory = () => new Memcached('127.0.0.1:11211', 10);
}
export const prisma = new CustomPrisma();
```

## Stack trace / Error message

```code
C:\Users\Kryfulli\...\node_modules\cached-prisma\node_modules\.prisma\client\index.js:3
    throw new Error(

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (C:\Users\Kryfulli\...\node_modules\cached-prisma\node_modules\.prisma\client\index.js:3:11)
    at CachedPrisma.get (C:\Users\Kryfulli\...\node_modules\cached-prisma\dist\prisma\prisma.js:53:34)
    at Object.<anonymous> (C:\Users\Kryfulli\...\dist\src\db.js:11:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Kryfulli\...\dist\src\classes\AoHCharacter.js:13:17)
```

## Your Environment

Using VS Code, on Windows 10. Node My prisma version is the latest, 3.5.0. Node version is 16.13.0.

**Comment by JoelLefkowitz** [comment]
@Kryfulli Thanks for raising this, Ill have a look now

**Comment by JoelLefkowitz** [comment]
@Kryfulli, sorry for the long wait. It looks like you haven't generated the types for the prisma client. Running `prisma generate` will populate your node_modules folder with types compatible with your schema file. I've added a full example into the readme that walks you through all the steps required to provision and initialise your environment. 

Hope that helps.  If you still have errors please reopen this issue with more info.
