### ISSUE TITLE
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again

### ISSUE THREAD

**Issue by MrJackdaw** [JoelLefkowitz/cached-prisma#5]
# Bug Report
Hello; thanks for creating the library! I encountered a previous user's issue, which I think boils down to: **how do I get `cached-prisma` to see my files?** Hoping you can help. 

## Description
- Encountered this error when replacing a previous `PrismaClient` singleton with `new Prisma().client`. 
- Error occurs when running or building the app. 
- Code example will be shown below (hopefully to highlight my misunderstanding here)

## Is this a regression?

Unclear; it was reported in #3 , which was closed as a documentation issue. But I've followed the documentation and still get the error. 

## Minimal Reproduction
```typescript
// OLD - No errors
import { PrismaClient, User } from "@prisma/client";

export type CtxUser = Pick<User, "id" | "image" | "email">;
export const client = new PrismaClient();


// NEW - Results in reported error
import { User } from "@prisma/client"; // exists after 'npx prisma generate'
import { Prisma } from "cached-prisma";

export type CtxUser = Pick<User, "id" | "image" | "email">; // no error
export const client = new Prisma().client;
```

## Stack trace / Error message

```code
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/[TRUNCATED]/node_modules/cached-prisma/node_modules/.prisma/client/index.js:5:11)
    at Function.Prisma.clientFactory (/[TRUNCATED]/node_modules/cached-prisma/src/prisma.ts:59:20)
    at new Prisma (/[TRUNCATED]/node_modules/cached-prisma/src/prisma.ts:48:40)
    at Object.<anonymous> (/[TRUNCATED]/src/graphql/context.ts:20:33)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._compile (/[TRUNCATED]/node_modules/source-map-support/source-map-support.js:521:25)
    at Module.m._compile (/private/var/folders/_z/p84vt6bn29v8j3q_8xdcl_hc0000gn/T/ts-node-dev-hook-3284771350906466.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/_z/p84vt6bn29v8j3q_8xdcl_hc0000gn/T/ts-node-dev-hook-3284771350906466.js:114:20)
    at require.extensions.<computed> (/private/var/folders/_z/p84vt6bn29v8j3q_8xdcl_hc0000gn/T/ts-node-dev-hook-3284771350906466.js:71:20)
```

## Your Environment
```code
NodeJS: v21.5.0
```

**Comment by JoelLefkowitz** [comment]
Heya @MrJackdaw, thanks for opening this issue. I've tried to reproduce this locally but don't get any errors. Have you tried rerunning `prisma generate`? If this issue persists please create a public repository that reproduces the bug and I can take a look :)

**Comment by MrJackdaw** [comment]
> Heya @MrJackdaw, thanks for opening this issue. I've tried to reproduce this locally but don't get any errors. Have you tried rerunning `prisma generate`? If this issue persists please create a public repository that reproduces the bug and I can take a look :)

Hey thanks for responding so quickly! I have indeed run `prisma generate` -- and we have a pre-start script so that NPM always runs it before `start`. In all cases, the rest of the application can see the generated types in `@prisma/client` (since there are no type errors).

Could it be an order-of-operations thing? (As in, am I initializing things in the wrong order?) I feel like I'm missing something minor but obvious. 
The compiled cached-prisma `PrismaClient` class looks like this:

```typescript
class PrismaClient {
  constructor() {
    throw new Error(
      `@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues`,
    )
  }
}
```
Is that expected?
Source: `node_modules/cached-prisma/node_modules/.prisma/client/index.js`

**Comment by MrJackdaw** [comment]
@JoelLefkowitz problem solved! 
When you get a moment, can you please add a note for those migrating from an existing prisma install? (This was basically the "small thing" I was missing). Thanks again for taking time to respond here, and for your library! 

---

## Migrating an Existing Prisma install
⚠️ **Please uninstall your existing (local) `prisma` and `@prisma/client` dependencies!** If you don't, your application may throw a `@prisma/client did not initialize yet` error.  `cached-prisma` is a drop-in replacement for both. 

If you are already using a similar pattern in your app (i.e. exporting a single `PrismaClient` instance), here's a quick way to swap: 

### Old Method
```typescript
import { PrismaClient } from "@prisma/client";

export const client = new PrismaClient();
```

### New Method

```typescript
import { Prisma } from "cached-prisma";

export const client = new Prisma().client;
```
