### ISSUE TITLE
warn Versions of prisma@5.17.0 and @prisma/client@5.9.1 don't match.

### ISSUE THREAD

**Issue by stormbeforesunsetbee** [JoelLefkowitz/cached-prisma#9]
warn Versions of prisma@5.17.0 and @prisma/client@5.9.1 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.

**Comment by JoelLefkowitz** [comment]
@stormbeforesunsetbee thank you for raising this, it is fixed by #11

**Comment by JoelLefkowitz** [comment]
@stormbeforesunsetbee [1.3.2](https://www.npmjs.com/package/cached-prisma/v/1.3.2) published
